---
- name: Verify if the sudo package is installed
  ansible.builtin.command: "rpm -q {{ pkg }}" # noqa command-instead-of-module
  register: pkg_installed
  ignore_errors: true
  changed_when: "pkg_installed.rc != 0"

- name: Install the sudo package
  ansible.builtin.command: "yum install -y {{ pkg }}" # noqa command-instead-of-module
  changed_when: true
  when: "pkg_installed.rc != 0"
