---
# tasks file for sudo
- name: set OS related variables
  include_vars: '{{ os_vars }}'
  with_first_found:
    - '{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml'
    - '{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml'
    - '{{ ansible_distribution }}.yml'
    - '{{ ansible_os_family }}.yml'
    - defaults.yml
  loop_control:
    loop_var: os_vars

- name: install sudo packages
  include_tasks: '{{ install_sudo }}'
  with_first_found:
    - 'install_sudo/{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml'
    - 'install_sudo/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml'
    - 'install_sudo/{{ ansible_distribution }}.yml'
    - 'install_sudo/{{ ansible_os_family }}.yml'
    - install_sudo/defaults.yml
  loop_control:
    loop_var: install_sudo
  when: sudo_packages is defined

- name: ensure '{{ sudo_sudoers_d }}' exists
  file:
    path: '{{ sudo_sudoers_d }}'
    state: directory
    owner: '0'
    group: '0'
    mode: '0750'

- name: enable sudo_sudoers_d
  lineinfile:
    path: '{{ sudo_sudoers }}'
    regexp: '#includedir {{ sudo_sudoers_d }}'
    line:  '#includedir {{ sudo_sudoers_d }}'
    state: present
    validate: '{{ sudo_visudo }} -cf %s'

- name: set up sudoers_linesinfile
  include_tasks: 'sudoers_linesinfile.yml'
  when:
    - sudo is defined
    - sudo.sudoers_linesinfile is defined

- name: set up sudoers_d_files
  include_tasks: 'sudoers_d_files.yml'
  when:
    - sudo is defined
    - sudo.sudoers_d_files is defined
