---
- name: Delete sudo_file.path
  ansible.builtin.file:
    path: "{{ sudo_sudoers_d }}/{{ sudo_file.path }}"
    state: absent
  when:
    - sudo_file.state is defined
    - sudo_file.state == "absent"

- name: Create sudo_file.path
  ansible.builtin.copy:
    dest: "{{ sudo_sudoers_d }}/{{ sudo_file.path }}"
    content: "{{ sudo_file.content | default(omit) }}"
    backup: "{{ sudo_file.backup | default(omit) }}"
    owner: "0"
    group: "0"
    mode: "0440"
    validate: "{{ sudo_visudo }} -cf %s"
  when:
    ( sudo_file.state is not defined ) or ( sudo_file.state == "present" )
